swagger: "2.0"
info:
  title: "Urlshortener"
  version: "0.0.1"
basePath: "/v1"
paths:
  /shrink:
    post:
      summary: "Сократить ссылку"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/SourceLink"
      responses:
        200:
          description: "Успешная операция"
          schema:
            type: object
            allOf:
              - { $ref: '#/definitions/ApiResult' }
              - { properties: { data: {type: object, $ref: "#/definitions/ProcessedLink"}, success: {type: boolean, example: true } } }
        400:
          description: "Ошибка валидации параметров"
          schema:
            type: object
            allOf:
              - { $ref: '#/definitions/ApiResult' }
              - { properties: { success: {type: boolean, example: false } } }
        500:
          description: "Внутренняя ошибка"
          schema:
            type: object
            allOf:
              - { $ref: '#/definitions/ApiResult' }
              - { properties: { success: {type: boolean, example: false } } }
  /{shortCode}:
    get:
      summary: "Represents a short URL. Tracks the visit and redirects tio the corresponding long URL"
      parameters:
        - in: "path"
          name: "shortCode"
          description: "The short code to resolve"
          required: true
          type: "string"
        - in: "header"
          name: "user_agent"
          required: false
          type: "string"
      responses:
        302:
          description: "Visit properly tracked and redirected"
          headers:
            Location:
              type: string
              description: "Redirect url"
          schema:
            type: object
            allOf:
              - { $ref: '#/definitions/ApiResult' }
              - { properties: { data: {type: object, $ref: "#/definitions/RedirectUrl"}, success: {type: boolean, example: true } } }
        404:
          description: "Ссылка не найдена"
          schema:
            type: object
            allOf:
              - { $ref: '#/definitions/ApiResult' }
              - { properties: { success: {type: boolean, example: false } } }
        500:
          description: "Внутренняя ошибка"
          schema:
            type: object
            allOf:
              - { $ref: '#/definitions/ApiResult' }
              - { properties: { success: {type: boolean, example: false } } }

definitions:
  ApiResult:
    description: "Стандартизированный ответ API"
    properties:
      data:
        description: "Данные"
        type: object
      meta:
        description: "Разная опциональная дополнительная информация"
        type: object
      errors:
        description: "Список ошибок"
        type: object
      success:
        description: "Результат выполнения запроса (true - нет ошибки, false - ошибка)"
        type: boolean
        example: true
    type: object
  SourceLink:
    type: object
    description: "Исходная длинная ссылка"
    required:
      - long_url
    properties:
      long_url:
        type: string
        format: url

  ProcessedLink:
    type: object
    description: "Сокращённая ссылка"
    properties:
      id:
        type: string
      long_url:
        type: string
        format: url
      short_url:
        type: string
        format: url
  RedirectUrl:
    type: object
    description: "URL для редиректа"
    properties:
      long_url:
        type: string
        format: url