// Code generated by MockGen. DO NOT EDIT.
// Source: mapper.go

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	operations "github.com/dimuska139/urlshortener/internal/gen/restapi/operations"
	models "github.com/dimuska139/urlshortener/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMapper is a mock of Mapper interface.
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
}

// MockMapperMockRecorder is the mock recorder for MockMapper.
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance.
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// PostShrinkOKBody mocks base method.
func (m *MockMapper) PostShrinkOKBody(link models.Link) *operations.PostShrinkOKBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostShrinkOKBody", link)
	ret0, _ := ret[0].(*operations.PostShrinkOKBody)
	return ret0
}

// PostShrinkOKBody indicates an expected call of PostShrinkOKBody.
func (mr *MockMapperMockRecorder) PostShrinkOKBody(link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostShrinkOKBody", reflect.TypeOf((*MockMapper)(nil).PostShrinkOKBody), link)
}
